import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F4F6F5" },
  content: {
    padding: 24,
    gap: 20,
    width: "100%",
    maxWidth: 680,
    alignSelf: "center",
    paddingBottom: 48,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#172522",
    letterSpacing: 0,
  },
  subtitle: { fontSize: 16, color: "#596561", lineHeight: 24 },
  label: { fontSize: 14, fontWeight: "600", color: "#34443E" },
  field: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#B9C5BF",
    borderRadius: 6,
    padding: 14,
    minHeight: 48,
    color: "#172522",
    fontSize: 16,
  },
  button: {
    backgroundColor: "#17634B",
    borderRadius: 6,
    minHeight: 48,
    padding: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  secondary: {
    minHeight: 48,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  link: {
    color: "#17634B",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  error: { color: "#A52B36", fontSize: 15, lineHeight: 22 },
  group: { gap: 8 },
  row: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
  },
  device: {
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#DCE3DE",
    padding: 20,
    gap: 16,
  },
  reading: { fontSize: 25, fontWeight: "600", color: "#172522" },
});
